//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysPronatec.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Atendimento
    {
        public Atendimento()
        {
            this.Curso = new HashSet<Curso>();
        }
    
        public long NumeroAtendimento { get; set; }
        public string Cadastrador { get; set; }
        public System.DateTime DataCadastro { get; set; }
        public string UnidadeAtendimento { get; set; }
        public string RespresentanteCadastro { get; set; }
        public string FormadeAcesso { get; set; }
        public long CandidatoIDPessoa { get; set; }
    
        public virtual Candidato Candidato { get; set; }
        public virtual ICollection<Curso> Curso { get; set; }
    }
}
