//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysPronatec.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidato
    {
        public Candidato()
        {
            this.Atendimento = new HashSet<Atendimento>();
            this.Telefone = new HashSet<Telefone>();
        }
    
        public long IDPessoa { get; set; }
        public long NIS { get; set; }
        public string Profissao { get; set; }
        public string DisponibilidadeHoraio { get; set; }
        public long EscolaridadeIdEscolaridade { get; set; }
        public long AtendimentoNumeroAtendimento { get; set; }
    
        public virtual ICollection<Atendimento> Atendimento { get; set; }
        public virtual Pessoa Pessoa { get; set; }
        public virtual Escolaridade Escolaridade { get; set; }
        public virtual ICollection<Telefone> Telefone { get; set; }
    }
}
