//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysPronatec.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Curso
    {
        public short IdCurso { get; set; }
        public string NomeCurso { get; set; }
        public long NumeroAtendimento { get; set; }
        public string Local { get; set; }
    
        public virtual Atendimento Atendimento { get; set; }
    }
}
