//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysPronatec.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Endereço
    {
        public Endereço()
        {
            this.Pessoa = new HashSet<Pessoa>();
        }
    
        public short IDEndereco { get; set; }
        public string Rua { get; set; }
        public string Bairro { get; set; }
        public short NumeroCasa { get; set; }
        public string Complemento { get; set; }
        public long PessoaIDPessoa { get; set; }
    
        public virtual ICollection<Pessoa> Pessoa { get; set; }
    }
}
