//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysPronatec.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Escolaridade
    {
        public Escolaridade()
        {
            this.Candidato = new HashSet<Candidato>();
        }
    
        public long IdEscolaridade { get; set; }
        public string Escolaridade1 { get; set; }
    
        public virtual ICollection<Candidato> Candidato { get; set; }
    }
}
