//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysPronatec.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Telefone
    {
        public int IDTelefone { get; set; }
        public long IDPessoa { get; set; }
        public Nullable<short> Residencial { get; set; }
        public short Celular { get; set; }
    
        public virtual Candidato Candidato { get; set; }
    }
}
